# Generated by Django 3.2 on 2021-04-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210413_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.RenameModel(
            old_name='All',
            new_name='AllModels',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='tags',
            field=models.ManyToManyField(through='myapp.AllModels', to='myapp.TagModel'),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='tasks',
            field=models.ManyToManyField(through='myapp.AllModels', to='myapp.TaskModel'),
        ),
        migrations.AlterField(
            model_name='allmodels',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tagmodel'),
        ),
        migrations.AlterField(
            model_name='allmodels',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.taskmodel'),
        ),
    ]
