# Generated by Django 3.2 on 2021-04-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210413_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='tags',
        ),
        migrations.RenameModel(
            old_name='AllModels',
            new_name='All',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(through='myapp.All', to='myapp.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(through='myapp.All', to='myapp.Task'),
        ),
        migrations.AlterField(
            model_name='all',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tag'),
        ),
        migrations.AlterField(
            model_name='all',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task'),
        ),
    ]
